create table if not exists feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  rating int,
  message text,
  status text default 'new' -- new, read, archived
);

-- Enable RLS
alter table feedback enable row level security;

-- Allow public to insert feedback
create policy "Allow public insert to feedback"
  on feedback for insert
  with check (true);

-- Allow admins to view feedback (assuming authenticated users are admins for now or using service role)
-- For simplicity in this project context, we often rely on service role or authenticated users.
create policy "Allow authenticated view feedback"
  on feedback for select
  using (auth.role() = 'authenticated');
