-- Create a table for Public Profiles (linked to Auth)
create table profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  primary key (id),
  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for Products (Shoes)
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  brand text not null,
  size numeric not null, -- e.g. 9.5
  size_type text default 'US', -- US, UK, EU
  price numeric not null,
  condition text not null, -- 'New', 'Like New', 'Good', 'Fair'
  status text default 'available', -- 'available', 'reserved', 'sold'
  images text[] -- Array of image URLs
);

alter table products enable row level security;

-- Allow read access to everyone
create policy "Products are viewable by everyone."
  on products for select
  using ( true );

-- Allow write access only to authenticated users (Admins)
-- For simplicity, we assume any logged-in user is an admin for now, 
-- or you can add a specific check if you have multiple users.
create policy "Authenticated users can insert products."
  on products for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update products."
  on products for update
  using ( auth.role() = 'authenticated' );

-- Storage Bucket Policy (You need to create a bucket named 'shoe-images' in the dashboard first)
-- Then run this to allow public access to view images
-- (This is usually done via the Storage UI, but good to know)
