
-- Create a table for Orders/Reservations
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_id bigint references products(id) not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  status text default 'pending' -- 'pending', 'completed', 'cancelled'
);

alter table orders enable row level security;

-- Allow anyone to create an order (Public reservation)
create policy "Anyone can create an order."
  on orders for insert
  with check ( true );

-- Only admins can view orders
create policy "Authenticated users can view orders."
  on orders for select
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can update orders."
  on orders for update
  using ( auth.role() = 'authenticated' );
